module.exports = {
  "1": "lucataco/animeganv2:ed7a01649f83cc69efc52da09f18214be0c3023f3b3bca3d903c210f193ca9c2",
  "2": "tencentarc/gfpgan:latest",
  "3": "cjwbw/anime-style-v1",
  "4": "cjwbw/anime-style-v2",
  "5": "cjwbw/anime-style-v3",
  "6": "cjwbw/anime-style-v4",
  "7": "cjwbw/anime-style-v5",
  "8": "cjwbw/anime-style-christmas",
  "9": "cjwbw/anime-onepiece",
  "10": "cjwbw/anime-oshi-no-ko",
  "11": "cjwbw/anime-naruto",
  "12": "cjwbw/anime-dbz",
  "13": "cjwbw/anime-deathnote",
  "14": "cjwbw/anime-bleach",
  "15": "cjwbw/anime-aot",
  "16": "cjwbw/anime-jujutsu",
  "17": "cjwbw/anime-prince-of-tennis",
  "18": "cjwbw/anime-demonslayer",
  "19": "cjwbw/anime-fullmetal",
  "20": "cjwbw/anime-hero-academia",
  "21": "cjwbw/anime-drstone",
  "22": "cjwbw/anime-haikyuu",
  "23": "cjwbw/anime-ghibli-v1",
  "24": "cjwbw/anime-ghibli-v2",
  "25": "cjwbw/anime-webtoon"
};
